repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 4cbc74d53fe5634e58e0e65db7d28939c9cec3f7 # v0.12.7
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix]
      - id: ruff-format
        name: ruff (formatter)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/crate-ci/typos
    rev: 7735742fe15f92eb88e4660c70ae0184c4a57502 # v1.28.1
    hooks:
      - id: typos
        args: [--write-changes]
