[default.extend-words]
# Allow dataset-specific column names from Hillstrom dataset
womens = "womens"
mens = "mens"

[default.extend-identifiers]
# Author name in SciPy citation
VanderPlas = "VanderPlas"
